### ISSUE TITLE
Langsom load af emner i app, når der er mange brugerflader

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetApp#10]
Dette kan løses ved at lade app’en finde billederne fra internettet.

**Comment by kjoller** [comment]
Alle apps bliver pt. syncet, også usynlige sagsbehandlerapps og minimaps.
Synkroniser kun visse brugerflader. Hent kun synlige brugerflader. Sagsbehandler hentes hjemmefra

**Comment by KarenFrederiksen** [comment]
![image1](https://cloud.githubusercontent.com/assets/4989192/11334538/03e1374e-91d6-11e5-851d-c4744f845ae8.PNG)
Indberetningsemnerne bliver ikke synkroniseret rigtigt. Jeg kan vælge dem, men der står ikke hvad det er og billedet mangler.
