### ISSUE TITLE
Mange indberetninger med dårlig nøjagtighed - GPS'en må gerne blive aktiveret noget før

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetApp#19]
Vi får en del indberetninger, der er rigtig svære at lokalisere, idet nøjagtigheden af punktet kan være mere end 50 meter off (f.eks. laaaangt inde på en mark). 
Er det muligt at GPS'en kan søge efter placering ved opstart af app'en, således placeringen muligvis bliver bedre?

Lige nu virker det som om GPS'en først begynder at lede efter placering når man har valgt punkt 'Brug gps punkt', hvorefter formularen kommer frem.

**Comment by kjoller** [comment]
@KarenFrederiksen, der er i brugerfladeopsætningen i positionswidget'en en mulighed for at sætte 'High Accuracy' og 'Vis nøjagtighed'. Er dette et issue med disse aktiveret? Hvis du har et link til en specifik løsning ville det være fantastisk :-)

**Comment by kjoller** [comment]
Vi sætter den til at starte ved app-start istedet for ved den enkelte løsning.

**Comment by kjoller** [comment]
Det ser ud til at GPS'en (på android i hvert fald) slet ikke bliver tændt. Det er ret essentielt

**Comment by KarenFrederiksen** [comment]
Jeg kan heller ikke få gps'en til at tænde iOS(9.1).
