### ISSUE TITLE
Funktionaliteten i online app’en er ikke den samme i IE og chrome

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetApp#20]
Kan det passe, at man ikke kan rette i status og/eller slette i IE 11? Når jeg prøver at åbne link fra email, åbnes der automatisk i IE, der er kommunens standard browser. Her skal jeg så logge ind, men cursoren er ikke den hånd, der kan ”åbne” de enkelte praj, men derimod en pil – der altså ikke kan åbne dem. Kan det passe at man ikke kan bruge sagsbehandler app’en sammen med IE11? Eller er der et eller andet jeg overser og kan ændre så det er muligt?

Funktionaliteten i online app’en er ikke den samme i IE og chrome. Når man åbner linket i IE kan man ikke klikke på de enkelte indberetninger. Det gælder både borger-app’en og sagsbeandler-app’en. Problemet er selvfølgelig størst i sagsbehandler-app’en. Problemet gør at sagsbehandleren ikke kan arbejde med indrapporteringen, hvis linket åbnes i IE. IE er standard browser i Dragør Kommune og det kan jeg nok ikke ændre på. Hvis jeg skal kunne udbrede brugen af app’en er det derfor ret essentielt at der er den samme funktionalitet i app’en uanset hvilken browser, der benyttes. Jeg ved ikke hvor stort et issue det er, men kan det løses? Eller er det noget med, at jeg skal arbejde på at få chrome rullet ud til sagsbehandlerne? 

(Anders, Dragør)

**Comment by KarenFrederiksen** [comment]
Denne bug hænger sammen med to andre issues: https://github.com/os2geo/RapportFraStedetMiniMap/issues/4
https://github.com/os2geo/RapportFraStedetMiniMap/issues/3

**Comment by kjoller** [comment]
Link fra Frederiksberg, hvor man efter at have lukket boksen fra den indberetning der åbner ikke kan komme til den igen. Menuen kan ikke åbnes, og man sidder dermed fast.

http://geo.os2geo.dk/couchdb/app-d2121ee08caf832b73a160f9ea022ad9/_design/app2/web/index2.html#/organizations/db8a996dc6a67ee64e8b72730a22b15a/ac3d5b62ebb8d7ce847c609711f6602f/menu?layer=ac3d5b62ebb8d7ce847c609711f40cb2&id=bc6298b808cb193d533822d70c8d6cd3

Formodes at blive løst sammen med 
https://github.com/os2geo/RapportFraStedetMiniMap/issues/4

**Comment by runetvilum** [comment]
skal løses ved os2geo/RapportFraStedetMiniMap#9
