### ISSUE TITLE
Dårlig synkronisering til app

### ISSUE THREAD

**Issue by kjoller** [os2geo/RapportFraStedetApp#22]
Ting kører langsomt.

**Comment by HasseHauch** [comment]
Dette skal undersøges nærmere, for at finde den helt rigtige løsning.

**Comment by KarenFrederiksen** [comment]
Dette issue er muligvis sammenfaldende med #12, der er også en mulig løsning på dette issue.

**Comment by runetvilum** [comment]
Der er flere ting som gør synkroniseringen langsom:
1. Billeder gemmes i samme dokument som indberetningen.
2. CouchDB synkroniserer via HTTP long polling. Der sendes en masse header informationer og ekstra kald i forhold til websockets.
   Websockets er langt mere efektivt og vil også betyde mobilenheder bruger mindre batteri.
3. Data lagres i lokal sqlite database på mobilenheden ved at bruge et native plugin. Hvis der synkroniseres mellem flere databaser samtidigt, bliver det meget langsomt.
   Der er kommet ny version af sqlite plugin som skal testes for performance.
   I stedet for at synkronisere til flere database kunne der anvendes en workqueue så der kun sendes data til én database. serverscripts tager så jobs fra workqueue og sender data til forskellige databaser.
4. Indberetninger valideres både på klienten og på serveren. For at kunne validere indberetninger på klienten skal straksafgørelsespolygonen og skemaet hentes. Straksafgørelsespolygoner fylder meget og den samme polygon kan ikke genbruges i flere løsninger.
   Det kan gå galt hvis de ikke er opdateret på klienten!

Løsningen kunne være følgende:
1. Benyt en workqueue og opdel lagringen af indberetninger og billeder.
   Nye indberetninger og ændring af indberetninger gemmes i en workqueue i en lokal sqlite database. Når indberetningen er blevet replikeret til serveren, slettes den fra workqueue'en.
   Serveren gemmer indberetningen uden billeder (eller måske med thumbnails) i én database og billederne gemmes på Amazon S3 (filserver hvorfra de kan vises via url).
2. Benyt websockets og skift fra CouchDB til Firebase. Firebase synkronisere lynhurtigt data.
   Data lever kun i hukommelsen på mobilenheden (Firebase arbejder på en persistent løsning). Det betyder at hvis app'en genstartes skal data hentes igen. Ændringer er dog gemt i workqueue og går ikke tabt.
3. Ved at skifte til workqueue og firebase er der kun brug for én sqlite database (til workqueue). Når data er hentet fra serveren lever de i hukommelsen og er dermed lynhurtige at vise.
4. Drop validering af data på klienten. Data valideres på serveren i forbindelse med behandling af indberetninger i workqueue. Hvis en indberetning ikke er gyldig ændres status på den til ikke gyldig. Denne ændring synkroniseres til den mobileenhed som har den pågældende indberetning i sin workqueue. App'en oplyser nu brugeren om at valideringsfejlen og brugeren får mulighed for at ændre indberetningen.

**Comment by kjoller** [comment]
Rune kigger nu på ny version af SQLite-plugin, og håber at det kan afhjælpe nogen af performance-issues

**Comment by HasseHauch** [comment]
Forsøges løst ved issues #10, #24 og #25

**Comment by kjoller** [comment]
Jeg fjerner denne fra September-iterationen, da den er delt op i små-issues. Hvis ikke de løser problemet, så må vi kigge på det i en senere iteration
