### ISSUE TITLE
Lokal SQLite-database langsom

### ISSUE THREAD

**Issue by HasseHauch** [os2geo/RapportFraStedetApp#24]
Test ny version af SQLite-plugin, håber at det kan afhjælpe nogen af performance-issues

**Comment by kjoller** [comment]
Performance-issues er ikke løst i ny version af plugin. Index-db er en bredt understøttet teknologi i mobile browsere, der kører hurtigere.

**Comment by kjoller** [comment]
SQLite plugine'et har brugt pouchDB, der ikke har haft mulighed for at styre hvad der bliver synkroniseret.
