### ISSUE TITLE
Scroll-baren mangler i formularen

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetApp#4]
Scroll hjulet på musen virker ikke i formularen. Problem ved indberetning fra pc.

**Comment by kjoller** [comment]
Den virker ikke helt ordentligt i Firefox. Scroll-hjulet virker som sådan, men man bliver træt i fingeren inden den når ned.

**Comment by kjoller** [comment]
Scroll-hjulet virker nu. På grund af det mobile interface er der ikke mulighed for en gammeldags scroll-bar. Filter-boksen er stadig langsomt fungerende i Firefox, men det er et grænsetilfælde.
